development:
  adapter: postgresql
  encoding: unicode
  database: sits_development
  pool: 5
  username: khrystynaklochko
  password: sits

  test:
  adapter: postgresql
  encoding: unicode
  database: sits_test
  pool: 5
  username: khrystynaklochko
  password: sits